- acitoolkit/acibaseobject.py
I ran into an issue where I was setting the description on an object, committing it, and it was not showing up in the UI. It looks like the 'descr' attribute was never getting set.
> Set the description if the user supplies it

- applications/endpointtracker/aci-endpoint-tracker-gui.py
Add an optional command line argument to aci-endpoint-tracker-gui that lets you choose the port to listen on (useful when you want to run endpoint tracker GUI and snapback applications on the same host, say behind a reverse proxy)
> Add port to listen on command line argument to aci-endpoint-tracker-gui

- acitoolkit/aciphysobject.py
- acitoolkit/acitoolkit.py
Hi Michael,
Here are a few minor things that I had to tweak in the toolkit to automate a deployment. More may be coming in the next few days. It would be great if these could be merged upstream. I believe they are not intrusive. However, special attention should be payed to the one that deals with the 'allvlans' physical domain. For me it's the most important one (since I cannot hack it directly from my app), but changes the behavior of the toolkit slightly. 
I would be up to implement them differently if you come up with a cleaner way. Let me know.
Thanks and best regards,
Luis.
CHANGELOG:
- Add the ability to supply 'scope' for a Subnet.	
- Add the ability to pass encap_mode, so 'untagged' can be set through the constructor. Currently, the only way is to access the encap_mode directly. …
> Add miscellaneous functionality to the toolkit

- acitoolkit/__init__.py
- acitoolkit/aciConcreteLib.py
- acitoolkit/acibaseobject.py
- acitoolkit/aciphysobject.py
- acitoolkit/acitoolkit.py
import of the acitoolkit now works with python3, related to issue #73
> Fixed import error on python3 #73

- applications/eventfeeds/eventfeeds.py
In the previous revision each Atom Feed item was simply 'APIC', this commit will instead use the name of the object that generated the event. This looks better in Atom Feed readers.
Changed the logging to use %s interpolation and renamed some variables to not shadow outer scope as recommended by Pylint.
> Use object name as feed entry author and apply Pylint recommendations

- acitoolkit/acisession.py
Warning appears when session created and executed any commands. Warning looks like:
.../python2.7/site-packages/requests/packages/urllib3/connectionpool.py:768: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
InsecureRequestWarning)
> Fix of InsecureRequestWarning warning from urllib3 module

- acitoolkit/acibaseobject.py
Avoid "NameError: name 'unicode' is not defined" error.
> python 3 compatibility

- acitoolkit/acibaseobject.py
- acitoolkit/acitoolkit.py
Does this pass test_get_deep_tenants?
> Pass rsp-subtree-class query parameter only when limit_to has elements

- acitoolkit/acitoolkit.py
- tests/acitoolkit_test.py
> Standardize unicast routing attribute as BridgeDomain.unicast_route.

- acitoolkit/acitoolkit.py
- tests/acitoolkit_test.py
Contract -> ContractSubject and Filter -> FilterEntry are now independent from each other, this should better reflect the ACI MIT.
Changes made:
- Filter got it's own '.get_deep' method
- Parent of Filter should now be a Tenant Object
- ContractSubject has now a 'relation' to Filter Objects (instead of Parent/Child)
- add_filter method to add a Filter to a ContractSubject
- get_filter method to retrieve all Filters for a ContractSubject
- get and get_by_name_and_tenant methods for the Filter class
- _extract_relationships method for the ContractSubject Object, this rebuilds the
relations between ContractSubject and Filters
- added some internal help classes like '_get_apic_classes'
> Redesign of the relationships and dependencies of Contract/ContractSubject/Filter/FilterEntry

- acitoolkit/acitoolkit.py
For containers integration, since the policy is rendered by an orchestrator which knows the location of epg deployment, immediate resolution for epg domain bindings give faster convergence with accurate rendering of the policy
> set resolution and deployment immediacy for epg

- acitoolkit/acitoolkit.py
Added code to allow users to set the mutidestination flooding policy on an EPG. 
How to use it:
```
bd = BridgeDomain('my-bd', tenant)
bd.set_multidestination("encap-flood")
```
> Add the ability to set multidestination flooding policy on an EPG

- acitoolkit/acitoolkit.py
Hi,
This patch adds the ability to bind an static leaf to an EPG. I tried to imitate the model that the toolkit follows for the interfaces but unfortunately it wasn't possible, since one can add encapsulation information to an L2Interface but it doesn't make sense to do that for a Node object, so even if we could do epg.attach(node) where node is of type Node, we'd be missing the necessary encap information for the EPG binding.
I am up to code this in a different way, but I studied the problem for a while and this implementation was the easiest and cleanest way I could find.
Please let me know. Best regards,
Luis.
PS: Here's code that consumes the new method.
```
epg = EPG("db-01", ap)
epg.add_static_leaf_binding(101, "vlan", 405)
epg.add_static_leaf_binding(102, "vlan", 406, …
```
> Add the ability to bind static leaves to an EPG.

- acitoolkit/acitoolkit.py
Currently, when constructing a Subnet object from APIC data, the scope attribute does not get populated. This patch fixes the problem.
> Fix bug: set up scope properly in Subnet

- acitoolkit/acitoolkit.py
[Resubmitting this PR so it can be merged straight away. Previous one conflicted.]
Add a few missing methods to the toolkit, for completeness and consistency. Note that some of the methods requested can be considered redundant (e.g. get_arp_flood() when is_arp_flood() already exists). The reason why they were added is because that allows an application to retrieve state of the policy and push it to a different APIC without having to figure out what kind of parameter needs to be passed to the setter (e.g otherwise one needs to figure out what value needs to be passed to "set_arp_flood() when is_arp_flood() returns True. In this case, we'd need to pass "yes" to the setter, making it slightly harder to code it).
> Minor enhancements (conflicts fixed)

- acitoolkit/acitoolkit.py
This patch fixes a bug introduced in d4d941a69d191d8885d64a288bea102bf5bf6983
The fabric also allows subnets being only 'shared'. Previous assumption was that scope had to be either 'public' or 'private' and that 'shared' could optionally be appended to them, but not appear on its own. The patch modifies the input validation logic to account for this and also updates the documentation of the method.
> Fix bug: subnet scope can be 'shared' on its own.

- acitoolkit/acitoolkit.py
Make VPC path generation deterministic by always using the lowest node id first. Currently, this is left to the way Python would construct a set. Code doing that is the following:
```
def _update_nodes(self):
"""Updates the nodes that are participating in this PortChannel"""
nodes = []
for interface in self._interfaces:
nodes.append(interface.node)
self._nodes = set(nodes)
```
This patch modifies _get_path() so the nodes are sorted if they weren't.
> Improve VPC path generation

- acitoolkit/acitoolkit.py
- tests/acitoolkit_test.py
Related to Point  '- Associated L3 Outs: (Name)' of Issue #61
There was already an 'add_l3out' implementation that referenced to OutsideEPG. I changed this to OutsideL3 and added a proper resolution to the BridgeDomain class.
> Fixes #61, print Statement fix for python3

- acitoolkit/acitoolkit.py
Ensure comparisons of Subnet objects include the `addr` attribute - this should address #150 which occurs because the GUI generates all Subnet objects with an empty `name` attribute.
> Override __eq__ on Subnet class to also compare addr attribute

- acitoolkit/aciSearch.py
- acitoolkit/aciTable.py
- acitoolkit/acibaseobject.py
- acitoolkit/aciphysobject.py
- tests/aciphysobject_test.py
I rewrote some of the test to made them python3 compatible.
One test is currently failing for both python versions. I think this is related to the latest commits.
'test_get_deep_tenants'
> Made all test Python3 compatible

- acitoolkit/aciphysobject.py
Currently specifying a specific port is supported, however, there are several use cases where it is useful to get all of the interfaces of a specific node.
> Add the ability to specify a node in Interface.get()

- acitoolkit/acitoolkit.py
This PR is in reference to issue #173.
Check whether the name field in the attribute dictionary is populated before over writing the objects field.
> Fix #173, dont overwrite EPG name field if attribute list has empty/no value

- acitoolkit/acitoolkit.py
As described in #173, an issue has been introduced that causes an exception to be raised when determining if is_attribute_based is _true_ or _false_.
> Additional Fix #173, exception raised when referring to bool as string

- applications/lint/acilint.py
- setup.py
I added Error_005 to acilint.py to scan a fabric and identify any overlapping or duplicated subnets configured within a single Tenant/Context and updated setup.py to include the "ipaddr" module as a dependency as it is used for network subnet comparisons in the added error code.
> Add lint application check for overlapping subnets.

- acitoolkit/acisession.py
You get a new token whenever aaaRefresh is used. Added so self.token gets updated every time the refresh_login method is used.
http://www.cisco.com/c/en/us/td/docs/switches/datacenter/aci/apic/sw/1-x/api/rest/b_APIC_RESTful_API_User_Guide/b_IFC_RESTful_API_User_Guide_chapter_010.html
aaaRefresh—Sent as a GET message with no message body or as a POST message with the aaaLogin message body, this method resets the session timer. The response contains a new session token and cookie.
> Added so that token is updated when aaaRefresh is used

- applications/lint/acilint.py
- docs/source/acilint.rst
Added the following lint warnings:
W011 - Warn on Bidirectional TCP subjects in contract.
W012 - Warn on Bidirectional UDP subjects in contract.
W013 - Warn on Contracts with no Subjects.
W014 - Warn on Contracts with Subjects that have no Filters.
Updated the doc file to show these warnings.
> Add lint warnings for various contract conditions.

- acitoolkit/acitoolkit.py
This commit fixes #200.  Calling a get_deep on a Tenant did not fully populate the EPG’s children - specifically interface bindings and domain attachments.
Bindings fix:  When calling _extract_relationships on an EPG object in acitoolkit.py, if the EPG has multiple static bindings with the same vlan encapsulation, only one interface will be attached to the EPG.  This is because the L2Interface object name must be unique.  This fix updates the binding names so that they are unique.
Domain fix:  No domain object was created or attached when calling _extract_relationships.  Code to create and attach the domain was added.
> Commit to address Issue #200

- applications/lint/acilint.py
- Add contract for "Contract not provided within the same tenant".
- Remove redundant "No contract provided within this tenant".
> Update ACILint Warning 010 for better and less redundant output.

- acitoolkit/aciphysobject.py
Sometimes the available "speed" has the value "inherit" which is not useful when you need to know the actual speed of an interface (such as when computing %utilization). This was the minimal change I could make to the core toolkit to get the actual speed of the interface. operSt was already there, so I just duplicated what was in there.
> Add operSpeed to the Interface.info() attributes.

- acitoolkit/acibaseobject.py
This fixes an issue identified with the introduction of the `Tag` class.  
As a Tag can exist 'underneath' many different object types and acitookit has not yet implemented them all, there is a possibility that the function `_get_parent_from_dn` can cannot properly determine the parent object/name.  This PR does a check and returns `None` if the parent cannot be identified.
Maybe it might be a better idea to raise an error (ie, Not Implemented) or have a generic class that can handle this situation. Thoughts?
> Error not finding parent in _get_parent_from_dn

- applications/multisite/intersite.py
Bit of an odd one.  Running Intersite with a minimal configuration, I am getting a crash in the [`add_endpoint`](https://github.com/datacenter/acitoolkit/blob/master/applications/multisite/intersite.py#L230) method of `EndpointHandler`.  A deeper inspection looks like the error is caused by the Endpoint subscriber picking up Service Graph related events.  From my understanding, these objects are not traditional endpoints/epg's/etc and do not really have an accessable parent object?
Here is an example output of the error occuring:
```
heylook:multisite aidan$ python intersite.py --config config.json --debug verbose
Exception in thread Thread-4:
Traceback (most recent call last):
File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line …
```
> Intersite: skip endpoints that dont have accessable parent objects

- acitoolkit/acitoolkit.py
- applications/connection_search/aciConSearch.py
The documentation for the get_import_contract method for the ContractInterface class states that the method returns the imported contract, but it was returning a list containing the contract. Updated the code to match the docs.
Also updated the sample application that uses this method.
> Fix ContractInterface.get_import_contract() method to match docs

- acitoolkit/acitoolkit.py
Update to address issue #219 
Updated _get_all_epgs() private method (only used by get_all_consuming/providing_epgs() methods to return all types of EPGs, i.e. classes EPG, AnyEPG and OutsideEPG.
> Updates to make Contract.get_all_consuming/providing_epgs() return all types of EPGs

- applications/multisite/intersite.py
As it currently stands, when the intersite application does an initialisation (configuration load), it checks the local configuration file's list of contracts and compares it against the live (APIC) view.  If any of the contracts in the APIC view are not defined in the local configuration the intersite application will remove them.
I have a use case where the intersite application isn't the only source of truth for a particular l3out object and would prefer if it only cared about the contracts I have defined.  This PR adds the configuration option `noclean` to the intersite configuration for a specific l3out object which if set to `"True"` will skip the removal of contracts.
If you are okay with the concept of this PR, I will also update the intersite documentation to reflect these …
> [intersite] add option to not clean up potentially hanging contracts on first run

- applications/multisite/intersite_automator.py
- docs/source/intersite.rst
This is a basic implementation of an addition to intersite which automates the creation of intersite configuration by watching EPG tag events.  Once a new configuration has been generated, it is then loaded into intersite for regular operations.
As part of the configuration generation, it will also create new contracts (if configured to do so) and attach them to the new L3out networks.  It also has functionality to export the contracts attached to an L3out network to the original EPG owner (the tenant).
I have also updated the intersite documentation with information from related to PR #235
> [intersite] add functionality to automatically configure intersite using tags

- applications/endpointtracker/aci-endpoint-tracker.py
I encountered errors with endpointtracker deploying tables to a new DB, which results from an error: 
> Traceback (most recent call last):
>   File "./aci-endpoint-tracker.py", line 276, in <module>
>     main()
>   File "./aci-endpoint-tracker.py", line 272, in main
>     tracker(args)
>   File "./aci-endpoint-tracker.py", line 120, in tracker
>     c, cnx = connect_mysql(args)
>   File "./aci-endpoint-tracker.py", line 101, in connect_mysql
>     timestop  TIMESTAMP);''')
>   File "/usr/local/lib/python2.7/dist-packages/PyMySQL-0.7.9-py2.7.egg/pymysql/cursors.py", line 166, in execute
>     result = self._query(query)
>   File "/usr/local/lib/python2.7/dist-packages/PyMySQL-0.7.9-py2.7.egg/pymysql/cursors.py", line 322, in _query
>     conn.query(q)
>   File …
> Adjust defaults for 'timestop' and search query.

- acitoolkit/acisession.py
- acitoolkit/acitoolkitlib.py
- docs/source/tutorialsimpleconfig.rst
- tests/acitoolkit_test.py
Code:
- Requires pyopenssl module as a new - optional - dependency
- Add two new parameters to the session class cert_name and key
- Checks for presence of password or cert details
- Disables subscription if using certs (API does not support)
- Generates a unique signature for each GET or POST request
- Short circuits login retries if using cert auth
Misc:
- Extend library argparser to support cert parameters
- Add certificate login live test
- Update documentation with certificate auth example
This fixes #186 "Certificate based authentication"
One point of discussion would be adding a significant dependency: `pyopenssl`. With newer versions of pip it is a breeze to install (it will pick pre-built wheels automatically). Older versions of pip will require local compilation which could make …
> Add certificate based authentication to Session class

- acitoolkit/aciphysobject.py
- acitoolkit/acisession.py
- acitoolkit/acitoolkitlib.py
- docs/source/tutorialsimpleconfig.rst
- tests/acitoolkit_test.py
- App Center apps need to use a different class of user (aaaAppUser). This adds a flag to the Session class to support.
- Add support for requests with parameters that have been urlencoded
- Add extra tests for requests with parameters
- Tidy up logging and some requests URLs
> Further certificate authentication changes

- shippable.yml
- tests/aciphysobject_test.py
- Shippable is now run against Python3.5
- Updates some tests that used assertEquals to use the newer assertEqual
> Added Python3.5 to shippable, Updated Tests

- acitoolkit/acisession.py
- docs/source/tutorialsimpleconfig.rst
- tests/acitoolkit_test.py
appcenter supports subscription with certificate based authentication only for appcenter_user (for now).  This is via the new /api/requestAppToken which uses certificate to acquire a token and then normal aaaRefresh/subscriptionRefresh to maintain token and subscriptions.  All future queries can be performed with a valid token.
> add subscription support for appcenter_user with cert authentication

- Dockerfile
- setup.py
Update Dockerfile and setup.py to install graphviz libraries and pygraphviz module to support aci-diagram.
> fix graphviz requirements in docker images for aci-diagram to address issue #282

- README.md
- samples/aci-show-cdp.py
- samples/aci-show-contexts.py
- samples/aci-show-contracts.py
- samples/aci-show-domains.py
- samples/aci-show-epgs.py
- samples/aci-show-external-networks.py
- samples/aci-show-imported-contracts.py
- samples/aci-show-ip-int-brief.py
- samples/aci-show-subnets.py
- samples/aci-show-tenant-detail.py
- Add option to speficy tenant
- samples/aci-show-contexts.py
- samples/aci-show-contracts.py
- samples/aci-show-epgs.py
- samples/aci-show-external-networks.py
- samples/aci-show-imported-contracts.py
- samples/aci-show-ip-int-brief.py
- samples/aci-show-subnets.py
- I tested it in the following environment.
- [Python 2.7.13](https://github.com/sig9org/acitoolkit-alpine/tree/master/versions/library-2.7.13)
- [Python 3.5.3](https://github.com/sig9org/acitoolkit-alpine/tree/master/versions/library-3.5.3)
- [Python 3.6.1](https://github.com/sig9org/acitoolkit-alpine/tree/master/versions/library-3.6.1)
```sh
$ ./aci-show-contexts.py
Tenant         Context
-------------- ---------
common         copy
common         default
infra          overlay-1
mgmt           inb
mgmt           oob
``` …
> Add option to speficy tenant

- samples/aci-create-bd.py
- samples/aci-create-epg.py
- Add 'json output only' option to:
- samples/aci-create-bd.py
- samples/aci-create-epg.py
- I tested it in the following environment.
- [Python 2.7.13](https://github.com/sig9org/acitoolkit-alpine/tree/master/versions/library-2.7.13)
- [Python 3.5.3](https://github.com/sig9org/acitoolkit-alpine/tree/master/versions/library-3.5.3)
- [Python 3.6.1](https://github.com/sig9org/acitoolkit-alpine/tree/master/versions/library-3.6.1)
```
{'fvTenant': {'attributes': {'name': 'Tenant-A'}, 'children': [{'fvBD': {'attributes': {'name': 'Bd-A', 'unkMacUcastAct': 'proxy', 'arpFlood': 'no', 'multiDstPktAct': 'bd-flood', 'unicastRoute': 'yes', 'unkMcastAct': 'flood'}, 'children': [{'fvRsCtx': {'attributes': {'tnFvCtxName': 'Vrf-A'}}}, {'fvSubnet': {'attributes': {'ip': '192.168.1.1/24', 'name': '', …
```
> Add json output option

- acitoolkit/acitoolkit.py
Endpoint class _get method previously only returned the first IP associated with an endpoint. This fix utilizes the endpoint.secondary_ip variable to store any child IP objects associated with a particular ACI endpoint (MAC).
> Fix to Endpoint Class _get method to pull all IP's for an Endpoint.

- setup.py
Hey there,
I am trying to build the ACIToolkit in Python 2 however, an error occurs when installing DeepDiff as they dropped support for Python 2. The last version to use it was [`3.3.0`](https://github.com/seperman/deepdiff#deepdiff-v-407). 
This PR adds logic to check the version of Python running and if it's Python 2, install version 3.3.0.
> Fix for Python 2 DeepDiff

- acitoolkit/acibaseobject.py
- acitoolkit/acifakeapic.py
- acitoolkit/aciphysobject.py
- acitoolkit/acisession.py
- acitoolkit/acitoolkit.py
The way it is now, all log messages go to the "root" logger. This makes it hard to customize and filter messages with a config. Giving the loggers a name allows customization.
i.e. with object config:
```yml
loggers:
acitoolkit:
level: INFO
acitoolkit.acitoolkit:
level: WARN
```
> Use a named logger so they can be formatted and filtered

- applications/reports/Forms.py
- applications/reports/templates/credentials.html
The current "backend" code allows the use of both FQDN and IP Addressess when connecting to APIC, however, due to the IPAddress validator used in the flask form (Forms.py), non-ip addresses are marked as invalid on the GUI.
_Normally, APICs should be reachable on both FQDN or IP address so this is not a major showstopper, but i ran into this issue when trying to use the acitoolkit against the Devnet Sandbox (sandboxapicdc.cisco.com) which i guess is behind a Proxy/Load Balancer so it cannot be reached directly over IP._
The proposed merge includes:
- Change from Required to DataRequired validator (Required is an alias and might be deprecated)
- Imported ValidatorError to validate the Custom Validator
- Import of re and ipaddress modules for the Custom Validator
- Wrote a custom validator …
> Allow FQDNs on report Application GUI

- Dockerfile
Updated Dockerfile to allow files to build correctly in container.  Previous version (using ubuntu) failed to build.
> Update Dockerfile to use Debian Buster with 3.7.8

- acitoolkit/acitoolkit.py
modified the '`from collections import Sequence`' part in **acitoolkit.py** to stop ImportError for Python V3.9+
> Fix IportError
