datacenter/acitoolkit

acitoolkit/acisession.py

- In case the ACI is behind http:// and not https:// open the
websocket with ws: scheme instead of wss:
Signed-off-by: Giovanni Meo <gmeo@cisco.com>

Allow to connect to an http ACI

---

applications/aci-diagram/README.md
applications/aci-diagram/diagram.py

pull request to include aci-diagram application within the toolkit as per discussions with @michsmit99

add aci-diagram application to the toolkit

---

acitoolkit/acitoolkit.py
tests/acitoolkit_test.py

This is an enhancement on Issue #61 
The enchantments are:
- L2 Unknown Unicast 
- Unknown Multicast Flood
- ARP Flooding 
- Unicast Routing

Add Bridge Domain additions 

---

acitoolkit/acisession.py

Possible fix to the issue #76 , but maybe there is a other/better way?

Sorts the JSON that gets pushed to the ACI API

---

applications/snapback/aciconfigdb.py

This fixes the diff changes for domain files when taking snapshots.

Fix the diff changes that occurred in the domain JSON files

---

acitoolkit/acitoolkit.py

per issue #80.  Added get_path method to VMMDomain, and ability to attach VMMDomains to EPG correctly

ability to attach VMMDomains to EPG

---

acitoolkit/acitoolkit.py

set deployment immediacy on VMM domain

---

acitoolkit/acitoolkit.py
samples/aci-create-vmw-domain.py

VMM Domain Creation

---

samples/aci-show-ip-int-brief.py

add show ip int brief script

---

applications/snapback/aciconfigdb.py

It was a ValueError probably caused by newlines or backslashes

Fix bug when getting JSON data

---

Dockerfile

Dockerfile using precise repo, however is building from the latest ubuntu.

Fix Dockerfile from using old repo

---

acitoolkit/aciTable.py

Table.__init__(): simplified cell string conversion
Table.get_text(): simplified table transposition

Table simplification

---

acitoolkit/acitoolkit.py

This pull request adds the capability to attach L3 External Domains to External Routed network(OutsideEPG), as well as allows OutsideEPG to be attached to BridgeDomain, per #61

L3 Outside enhancements

---

docs/source/applications.rst
docs/source/fakeapic.rst

Add Fake APIC Documentation

---

applications/lint/acilint.py

secure_epg and nonsecure epg were only getting populated when an EPG had both tags.

Fix some logic in acilint compliance check

---

acitoolkit/acitoolkit.py
tests/acitoolkit_test.py

- New Classes that match the ContractSubject and Filter Objects inside of the Cisco ACI.
- Added Tests for this 2 Classes.
- Backward compatibility for FilterEntries that are directly attached to a Contract.
Any Inputs?
#116 & #117 will be fixed with this code

New Classes ContractSubject and Filter (Issue #116 and #117)

---

acitoolkit/acitoolkit.py
applications/endpointtracker/aci-endpoint-tracker.py

Added Parent Node IDs for VPC interfaces to insertion in the DB.

Ep tracker vpc nodes

---

acitoolkit/acitoolkit.py

This patch contains very minor style and documentation fixes.

Minor style and documentation fixes

---

acitoolkit/aciConcreteLib.py
acitoolkit/aciSearch.py

This pull requests contains commits that fix broken Python3.x support.

Fix print statements that break compatibility with Python3.x

---

samples/aci-show-subnets.py

Fix syntax error

---

applications/aci-diagram/diagram.py

Add --debug commandline option for aci-diagram to enable acitoolkit debug logging

Add --debug commandline option for aci-diagram

---

acitoolkit/acitoolkit.py

Created the stateful option to the FilterEntry so that scripts could
specify this new option.

Added stateful attribute to FilterEntry

---

acitoolkit/acitoolkit.py
samples/aci_demo_contract.py

I have added support Intra-EPG isolation feature in EPG.
Thanks to Alexander Skorokhodov (Cisco, Russia) for help and idea

Support of Intra-EPG isolation option added

---

applications/snapback/snapback.py
applications/snapback/snapback_test.py

implemented interface for diff of two snapshots given snapshots details in json
format,
changes for viewing a list of snapshots
and also unit testcases for the respective changes

filter snapshots using json inputs and also test cases for the related changes

---

samples/aci-copy-tenant-config.py

Existing code can't work properly. 
Add my code  # tenant_json = temp['fvTenant']['attributes']['name'] = tenant_name

Update aci-copy-tenant-config.py  

---

applications/configpush/apicservice.py

Using ipaddress.collapse_addresses create networks so the number of IP addresses entries is reduced.

for IP addresses in Criterion, construct networks with IP/net notation

---

applications/multisite/intersite_rest_server.py
setup.py

- Added CORS flask library and enabled it on REST server
- Return empty dictionary when no configuration file presented at startup
- Add functionality to POST configuration file when no configuration
file presented at startup

Intersite Orchestrator changes

---

samples/aci-find-ip.py

Added a new sample script to search for and match and IP address across all networks.

find IP address across all networks in the system

---

acitoolkit/acifakeapic.py
acitoolkit/acisession.py
acitoolkit/acitoolkit.py
acitoolkit/acitoolkitlib.py
applications/lint/acilint.py
setup.py

This Pull request will fix the broken python3 support. It's a work in progress, please wait with the merge.
Targets #229

Fix python3 support

---

acitoolkit/acibaseobject.py
acitoolkit/acitoolkit.py
samples/aci-show-tenant-faults.py
samples/aci-show-tenant-health.py

and a program to show the faults in a tenant.
Also added needed infra to subscribe to fault instances,to get fault
instances

program to show the health of all the tenants,

---

acitoolkit/__init__.py
acitoolkit/aciFaults.py
samples/aci-show-faults-by-domian.py
samples/aci-show-tenant-faults.py

aci-show-faults-by-domian.py -- sample program to find faults
by domian
aci-show-tenant-faults.py -- sample program to find faults of a tenant

aciFaults.py -- infra to subscribe and get faults

---

acitoolkit/acitoolkit.py
samples/aci-create-ospf-external.py
tests/acitoolkit_test.py

Not sure if OSPFInterface is the right place, maybe this would fit better directly under the OutsideL3?

Added areaType to OSPFInterface

---

acitoolkit/acitoolkit.py
tests/acitoolkit_test.py

Fix method set_scope of OutsideNetwork

---

acitoolkit/acitoolkit.py
tests/aci_configuration_randomizer.ini
tests/aci_configuration_randomizer.py

Added taboo
Classifying flows as 'drop’ if providing/comsuming EPG is protected by corresponding taboos
Generating negative flows
Moved all hardcoded values to ini file wherever possible
Set required filters for l2tp traffic type
Modified ContractSubject class to handle both ContractSubject and TabooContractSubject

taboo addition, negative flows generation and support for l2tp traffic type

---

README.md
samples/aci-create-bd.py

- Add aci-create-bd.py sample.
- Update README.md.

Add aci-create-bd.py sample.

---

samples/aci-create-epg.py

- Add aci-create-epg.py sample.

Add aci create epg spike

---

samples/aci-check-cluster.py
samples/aci-epg-reports-in-yaml.py
samples/aci-find-ip.py
samples/aci-get-interface-stats-from-nodes.py
samples/aci-get-tenantObject-from-json.py
samples/aci-raw-class-query.py
samples/aci-show-faults-by-domain.py
samples/aci-show-lldp.py
samples/aci-show-process.py
samples/aci-show-tenant-faults.py
samples/aci-show-tenant-health.py

- Add python interpreter declaration
- samples/aci-check-cluster.py
- samples/aci-epg-reports-in-yaml.py
- samples/aci-find-ip.py
- samples/aci-get-interface-stats-from-nodes.py
- samples/aci-get-tenantObject-from-json.py
- samples/aci-raw-class-query.py
- samples/aci-show-faults-by-domain.py
- samples/aci-show-lldp.py
- samples/aci-show-process.py
- samples/aci-show-tenant-faults.py
- samples/aci-show-tenant-health.py
- I tested it in the following environment.
- [Python 2.7.13](https://github.com/sig9org/acitoolkit-alpine/tree/master/versions/library-2.7.13)
- [Python 3.5.3](https://github.com/sig9org/acitoolkit-alpine/tree/master/versions/library-3.5.3)
- [Python 3.6.1](https://github.com/sig9org/acitoolkit-alpine/tree/master/versions/library-3.6.1)

Add python interpreter declaration

---

acitoolkit/__init__.py
applications/aci-diagram/diagram.py
applications/cli/acitoolkitcli.py
applications/inheritance/inheritance.py

Modify the code so that the CLI works in Python 3.

Python3 compatability

---

acitoolkit/aciConcreteLib.py
samples/aci-show-lldp.py

The files aciConcreteLib.py and aci-show-lldp.py were changed to provide local interface ID for each LLDP neighbor.

Change to show local interface ID when collecting LLDP information.

---

applications/lint/acilint.py
samples/aci-where-used.py

* Implements a simple sample script where an objects relationships can be displayed in tabular format.  
* Also sneaking in a quickfix to acilint.py replacing unicode w/ str for better python3 compatibility

Minor Enhancements

---

acitoolkit/acitoolkit.py

fix so that secondary endpoint IP-addresses are added to endpoint.secondary_ip

extend class Endpoint method _get with secondary_ip

---

samples/aci-show-endpoints.py

We use this in a DevNet Learning Lab, so my testing found one more sample with an old print statement.

Fixes one more python 3 print statement syntax

---

applications/reports/aci-report-switch.py

Fixes #357, Added required parenthesis for python3
